<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="E7841-Tech" name="com.LearningAPI.TestCases.UserRegistration_ForgotPasswordAPI" tests="2" failures="2" timestamp="22 Jan 2020 06:25:25 GMT" time="0.766" errors="0">
  <testcase name="UserRegistration_ForgotPasswordAPI_Test" time="0.309" classname="com.LearningAPI.TestCases.UserRegistration_ForgotPasswordAPI">
    <failure type="java.lang.AssertionError" message="Validation Response_param is :(message),Actual Response_paramvalue(Oops!! checksum error, please check your parameters.)did not match with Expected Response_paramvalue() expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Validation Response_param is :(message),Actual Response_paramvalue(Oops!! checksum error, please check your parameters.)did not match with Expected Response_paramvalue() expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.LearningAPI.TestCases.BaseTest.postExecutionvalidation(BaseTest.java:99)
at com.LearningAPI.TestCases.UserRegistration_ForgotPasswordAPI.UserRegistration_ForgotPasswordAPI_Test(UserRegistration_ForgotPasswordAPI.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- UserRegistration_ForgotPasswordAPI_Test -->
  <testcase name="UserRegistration_ForgotPasswordAPI_Test" time="0.457" classname="com.LearningAPI.TestCases.UserRegistration_ForgotPasswordAPI">
    <failure type="java.lang.AssertionError" message="Validation Response_param is :(message),Actual Response_paramvalue(Oops!! checksum error, please check your parameters.)did not match with Expected Response_paramvalue(Invalid OTP) expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Validation Response_param is :(message),Actual Response_paramvalue(Oops!! checksum error, please check your parameters.)did not match with Expected Response_paramvalue(Invalid OTP) expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.LearningAPI.TestCases.BaseTest.postExecutionvalidation(BaseTest.java:99)
at com.LearningAPI.TestCases.UserRegistration_ForgotPasswordAPI.UserRegistration_ForgotPasswordAPI_Test(UserRegistration_ForgotPasswordAPI.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- UserRegistration_ForgotPasswordAPI_Test -->
</testsuite> <!-- com.LearningAPI.TestCases.UserRegistration_ForgotPasswordAPI -->
